// Field configs mirror backend/app/schemas/validators.py exactly - field
// names, ranges, and choices must match so the API never rejects a
// well-formed frontend submission. `section` and `icon` are presentation-
// only metadata used by the frontend to group and label inputs; they are
// never sent to the API.

export const DISEASES = {
  diabetes: {
    slug: "diabetes",
    name: "Diabetes",
    icon: "droplet",
    tagline: "Screen for patterns associated with type 2 diabetes risk.",
    apiFn: "predictDiabetes",
    dataset: "Pima Indians Diabetes Dataset",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1, max: 120, step: 1, help: "Years", section: "Patient Profile" },
      { name: "preg", label: "Pregnancies", type: "number", min: 0, max: 30, step: 1, help: "Number of prior pregnancies", section: "Patient Profile" },
      { name: "bp", label: "Diastolic Blood Pressure", type: "number", min: 0, max: 250, step: 1, help: "mm Hg", section: "Clinical Measurements" },
      { name: "bmi", label: "Body Mass Index", type: "number", min: 0, max: 80, step: 0.1, help: "kg/m\u00b2", section: "Clinical Measurements" },
      { name: "st", label: "Skin Thickness", type: "number", min: 0, max: 100, step: 1, help: "Triceps skinfold thickness, mm", section: "Clinical Measurements" },
      { name: "glu", label: "Plasma Glucose", type: "number", min: 0, max: 400, step: 1, help: "mg/dL, 2-hour oral glucose tolerance test", section: "Laboratory Values" },
      { name: "ins", label: "Serum Insulin", type: "number", min: 0, max: 900, step: 1, help: "2-hour serum insulin, mu U/mL", section: "Laboratory Values" },
      { name: "dpf", label: "Diabetes Pedigree Function", type: "number", min: 0, max: 3, step: 0.001, help: "Genetic risk score", section: "Laboratory Values" },
    ],
  },
  heart: {
    slug: "heart",
    name: "Heart Disease",
    icon: "heart",
    tagline: "Screen for patterns associated with coronary heart disease.",
    apiFn: "predictHeart",
    dataset: "UCI Heart Disease Dataset",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1, max: 120, step: 1, section: "Patient Profile" },
      { name: "sex", label: "Sex", type: "select", options: [{ v: 0, l: "Female" }, { v: 1, l: "Male" }], section: "Patient Profile" },
      { name: "cp", label: "Chest Pain Type", type: "select", options: [{ v: 0, l: "Typical angina" }, { v: 1, l: "Atypical angina" }, { v: 2, l: "Non-anginal pain" }, { v: 3, l: "Asymptomatic" }], section: "Symptoms & Vitals" },
      { name: "trestbps", label: "Resting Blood Pressure", type: "number", min: 50, max: 260, step: 1, help: "mm Hg", section: "Symptoms & Vitals" },
      { name: "thalach", label: "Max Heart Rate Achieved", type: "number", min: 50, max: 250, step: 1, section: "Symptoms & Vitals" },
      { name: "exang", label: "Exercise-Induced Angina", type: "select", options: [{ v: 0, l: "No" }, { v: 1, l: "Yes" }], section: "Symptoms & Vitals" },
      { name: "oldpeak", label: "ST Depression (Exercise)", type: "number", min: 0, max: 10, step: 0.1, section: "Symptoms & Vitals" },
      { name: "chol", label: "Serum Cholesterol", type: "number", min: 50, max: 700, step: 1, help: "mg/dL", section: "Lab & Diagnostic Tests" },
      { name: "fbs", label: "Fasting Blood Sugar > 120 mg/dL", type: "select", options: [{ v: 0, l: "No" }, { v: 1, l: "Yes" }], section: "Lab & Diagnostic Tests" },
      { name: "restecg", label: "Resting ECG Result", type: "select", options: [{ v: 0, l: "Normal" }, { v: 1, l: "ST-T wave abnormality" }, { v: 2, l: "Left ventricular hypertrophy" }], section: "Lab & Diagnostic Tests" },
      { name: "slope", label: "Slope of Peak Exercise ST", type: "select", options: [{ v: 0, l: "Upsloping" }, { v: 1, l: "Flat" }, { v: 2, l: "Downsloping" }], section: "Lab & Diagnostic Tests" },
      { name: "ca", label: "Major Vessels Colored by Fluoroscopy", type: "select", options: [{ v: 0, l: "0" }, { v: 1, l: "1" }, { v: 2, l: "2" }, { v: 3, l: "3" }, { v: 4, l: "4" }], section: "Lab & Diagnostic Tests" },
      { name: "thal", label: "Thalassemia", type: "select", options: [{ v: 0, l: "Unknown" }, { v: 1, l: "Normal" }, { v: 2, l: "Fixed defect" }, { v: 3, l: "Reversible defect" }], section: "Lab & Diagnostic Tests" },
    ],
  },
  liver: {
    slug: "liver",
    name: "Liver Disease",
    icon: "liver",
    tagline: "Screen for patterns associated with liver dysfunction.",
    apiFn: "predictLiver",
    dataset: "UCI ILPD (Indian Liver Patient) Dataset",
    fields: [
      { name: "Age", label: "Age", type: "number", min: 1, max: 120, step: 1, section: "Patient Profile" },
      { name: "Gender", label: "Gender", type: "select", options: [{ v: "male", l: "Male" }, { v: "female", l: "Female" }], section: "Patient Profile" },
      { name: "Total_Bilirubin", label: "Total Bilirubin", type: "number", min: 0, max: 80, step: 0.1, help: "mg/dL", section: "Bilirubin & Enzymes" },
      { name: "Direct_Bilirubin", label: "Direct Bilirubin", type: "number", min: 0, max: 40, step: 0.1, help: "mg/dL", section: "Bilirubin & Enzymes" },
      { name: "AAP", label: "Alkaline Phosphotase", type: "number", min: 0, max: 3000, step: 1, help: "IU/L", section: "Bilirubin & Enzymes" },
      { name: "SAA_1", label: "Alamine Aminotransferase", type: "number", min: 0, max: 3000, step: 1, help: "IU/L", section: "Bilirubin & Enzymes" },
      { name: "SAA_2", label: "Aspartate Aminotransferase", type: "number", min: 0, max: 3000, step: 1, help: "IU/L", section: "Bilirubin & Enzymes" },
      { name: "Total_Protein", label: "Total Proteins", type: "number", min: 0, max: 15, step: 0.1, help: "g/dL", section: "Proteins" },
      { name: "ALB_Albumin", label: "Albumin", type: "number", min: 0, max: 10, step: 0.1, help: "g/dL", section: "Proteins" },
      { name: "AG_RATIO", label: "Albumin/Globulin Ratio", type: "number", min: 0, max: 5, step: 0.01, section: "Proteins" },
    ],
  },
  kidney: {
    slug: "kidney",
    name: "Chronic Kidney Disease",
    icon: "kidney",
    tagline: "Screen for patterns associated with chronic kidney disease.",
    apiFn: "predictKidney",
    dataset: "UCI Chronic Kidney Disease Dataset",
    fields: [
      { name: "age", label: "Age", type: "number", min: 0, max: 120, step: 1, section: "Patient Profile" },
      { name: "bp", label: "Blood Pressure", type: "number", min: 0, max: 250, step: 1, help: "mm Hg", section: "Patient Profile" },
      { name: "sg", label: "Specific Gravity", type: "number", min: 1.0, max: 1.03, step: 0.001, section: "Urinalysis" },
      { name: "al", label: "Albumin (urine)", type: "select", options: [0, 1, 2, 3, 4, 5].map((n) => ({ v: n, l: String(n) })), section: "Urinalysis" },
      { name: "su", label: "Sugar (urine)", type: "select", options: [0, 1, 2, 3, 4, 5].map((n) => ({ v: n, l: String(n) })), section: "Urinalysis" },
      { name: "rbc", label: "Red Blood Cells", type: "select", options: [{ v: "normal", l: "Normal" }, { v: "abnormal", l: "Abnormal" }], section: "Urinalysis" },
      { name: "pc", label: "Pus Cell", type: "select", options: [{ v: "normal", l: "Normal" }, { v: "abnormal", l: "Abnormal" }], section: "Urinalysis" },
      { name: "pcc", label: "Pus Cell Clumps", type: "select", options: [{ v: "notpresent", l: "Not present" }, { v: "present", l: "Present" }], section: "Urinalysis" },
      { name: "ba", label: "Bacteria", type: "select", options: [{ v: "notpresent", l: "Not present" }, { v: "present", l: "Present" }], section: "Urinalysis" },
      { name: "bgr", label: "Blood Glucose Random", type: "number", min: 0, max: 800, step: 1, help: "mg/dL", section: "Blood Chemistry" },
      { name: "bu", label: "Blood Urea", type: "number", min: 0, max: 400, step: 1, help: "mg/dL", section: "Blood Chemistry" },
      { name: "sc", label: "Serum Creatinine", type: "number", min: 0, max: 30, step: 0.1, help: "mg/dL", section: "Blood Chemistry" },
      { name: "sod", label: "Sodium", type: "number", min: 0, max: 200, step: 1, help: "mEq/L", section: "Blood Chemistry" },
      { name: "pot", label: "Potassium", type: "number", min: 0, max: 15, step: 0.1, help: "mEq/L", section: "Blood Chemistry" },
      { name: "hemo", label: "Hemoglobin", type: "number", min: 0, max: 20, step: 0.1, help: "g/dL", section: "Blood Chemistry" },
      { name: "pcv", label: "Packed Cell Volume", type: "number", min: 0, max: 60, step: 1, section: "Blood Chemistry" },
      { name: "wc", label: "White Blood Cell Count", type: "number", min: 0, max: 30000, step: 1, help: "cells/cumm", section: "Blood Chemistry" },
      { name: "rc", label: "Red Blood Cell Count", type: "number", min: 0, max: 8, step: 0.1, help: "millions/cmm", section: "Blood Chemistry" },
      { name: "htn", label: "Hypertension", type: "select", options: [{ v: "no", l: "No" }, { v: "yes", l: "Yes" }], section: "Clinical History" },
      { name: "dm", label: "Diabetes Mellitus", type: "select", options: [{ v: "no", l: "No" }, { v: "yes", l: "Yes" }], section: "Clinical History" },
      { name: "cad", label: "Coronary Artery Disease", type: "select", options: [{ v: "no", l: "No" }, { v: "yes", l: "Yes" }], section: "Clinical History" },
      { name: "appet", label: "Appetite", type: "select", options: [{ v: "good", l: "Good" }, { v: "poor", l: "Poor" }], section: "Clinical History" },
      { name: "pe", label: "Pedal Edema", type: "select", options: [{ v: "no", l: "No" }, { v: "yes", l: "Yes" }], section: "Clinical History" },
      { name: "ane", label: "Anemia", type: "select", options: [{ v: "no", l: "No" }, { v: "yes", l: "Yes" }], section: "Clinical History" },
    ],
  },
};

export const DISEASE_LIST = Object.values(DISEASES);
